### ISSUE TITLE
Making users aware of Rinkeby DAO being deprecated from AragonOS 0.5 to 0.6

### ISSUE THREAD

**Issue by jounih** [aragon/design#12]
Since AragonOS 0.5 -> 0.6 upgrade will break existing Rinkeby DAOs, we need to inform users this is happening, guide them to create new DAOs on 0.6 and provide access to old 0.5 DAOs for some period of time.

The proposed sequence:

**1. Inform users about the upcoming changes before 0.6 release**

Prototype: [https://invis.io/PUO9EOLQVW8#/322087315_WebApp-1366px_-_Banner](https://invis.io/PUO9EOLQVW8#/322087315_WebApp-1366px_-_Banner)

Design:

![webapp-1366px - banner 2x](https://user-images.githubusercontent.com/10109867/46237126-89324680-c37a-11e8-8a6a-a3ce39c43be8.jpg)

![webapp-1366px - banner modal 2x](https://user-images.githubusercontent.com/10109867/46237125-89324680-c37a-11e8-94ec-b846660052d2.jpg)

**2. After the 0.6 release has happened, someone accessing their previous DAO url at app.aragon.org/mydao won't work anymore. Guide users to the 0.5 backup location - old-app.aragon.org**

SVG animation: [http://helminen.co/clients/aragon/404.html](http://helminen.co/clients/aragon/404.html)

Prototype: [https://invis.io/PUO9EOLQVW8#/322684424_404](https://invis.io/PUO9EOLQVW8#/322684424_404)

Design:

![404 2x](https://user-images.githubusercontent.com/10109867/46237164-a9620580-c37a-11e8-9d06-2a66f8ba58b5.jpg)
![find rinkeby dao 2x](https://user-images.githubusercontent.com/10109867/46237165-a9620580-c37a-11e8-9db2-4d2c0b11108c.jpg)

**3. Keep telling users who access old 0.5 DAOs on old-app.aragon.org that the DAOs will be removed in early 2019 and they should recreate them**

Prototype: [https://invis.io/PUO9EOLQVW8#/322684427_WebApp-1366px_-_Banner_Old-App-aragon-one](https://invis.io/PUO9EOLQVW8#/322684427_WebApp-1366px_-_Banner_Old-App-aragon-one)

Design:

![webapp-1366px - banner old-app aragon one 2x](https://user-images.githubusercontent.com/10109867/46237172-b121aa00-c37a-11e8-91e9-d3cb010d9049.jpg)

![webapp-1366px - banner modal old-app aragon one 2x](https://user-images.githubusercontent.com/10109867/46237171-b121aa00-c37a-11e8-9319-a5a593a12675.jpg)

**Comment by sohkai** [comment]
Mostly implemented, but we still need to add:

> 3. Keep telling users who access old 0.5 DAOs on old-app.aragon.org that the DAOs will be removed in early 2019 and they should recreate them

**Comment by izqui** [comment]
In terms of wording I think it is very important that it doesn't seem that we are 'removing DAOs' but we are shutting down the interface that is used to interact with them.
