### ISSUE TITLE
Error screen for 404, app errors etc.

### ISSUE THREAD

**Issue by jounih** [aragon/design#14]
We need an error screen for several purposes - 404, React app crashing etc.

Below is a proposed generic design with those two above examples, but the implementation should be generic enough to have any type of error messaging

Prototype:

https://invis.io/DPOC874AS8V#/322924236_App_Error_

SVG animation:
http://helminen.co/clients/aragon/404.html

Design:

![app error 2x](https://user-images.githubusercontent.com/10109867/46304577-f88c7e00-c5a6-11e8-9e6b-e5b107251fe5.jpg)
![app error expanded 2x](https://user-images.githubusercontent.com/10109867/46304576-f7f3e780-c5a6-11e8-9efb-9a75df822c29.jpg)
![404 2x](https://user-images.githubusercontent.com/10109867/46304578-f88c7e00-c5a6-11e8-8913-a642d1d9ed1f.jpg)

**Comment by cfl0ws** [comment]
On [DATE] Aragon0S was upgraded from v0.5 to v0.6. DAO's created with v0.5 were deprecated then too. If you created your DAO before [DATE], you'll find it at [LINK1] until early 2019.

Otherwise, you can create a new DAO using v0.6 at [LINK2].

**Comment by sohkai** [comment]
Suggestion for copy:

> Rinkeby DAOs created with Aragon Core 0.5 were deprecated on [DATE 1] due to [underlying smart contract upgrades with aragonOS](link). If you were trying to access a DAO created before [DATE 1], you can access it at [old-app.aragon.org](link) until [DATE 2].

> However, we recommend migrating by creating a new DAO at [app.aragon.org](link).

**Comment by luisivan** [comment]
@sohkai just edited your comment replacing .one domains to .org
