### ISSUE TITLE
Use new font

### ISSUE THREAD

**Issue by luisivan** [aragon/design#19]
We are now using HK Grotesk for the website and brand, and I think it'd be worth trying in Aragon as well. @jounih, do you mind trying with it and seeing if it fits in there too?

**Comment by bpierre** [comment]
Demo: https://usemodify.com/fonts/hk-grotesk/

**Comment by jounih** [comment]
![webapp-1366px - survey details hk grotesk 2x](https://user-images.githubusercontent.com/10109867/48511882-ea8d7680-e84f-11e8-8cb6-390cb123490e.jpg)

I think it's a nice typeface, not sure about the display rendering at small sizes. 

@bpierre do you know if there is an easy way to replace the font on the live site locally, so I can see how it renders in the browser?

**Comment by luisivan** [comment]
Looks good to me!

**Comment by luisivan** [comment]
Closing this in favor of 
https://github.com/aragon/aragon/issues/490
