### ISSUE TITLE
Apps assets

### ISSUE THREAD

**Issue by bpierre** [aragon/design#30]
This is an issue to list the required assets we need for the apps.

What we need is:

- To define the required formats / dimensions for the different items.
- Some specification / documentation, similar to what [Apple](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/) or [Google](https://material.io/design/iconography/product-icons.html#icon-treatments) do (it could also be nice to combine it with some [guidelines](https://developer.apple.com/app-store/marketing/guidelines/)).
- We also need defaults icons, description etc. for unknown apps.

Items:

- Large icon (SVG or PNG)
- App Badge Icon (SVG or PNG)
- Menu Icon (SVG)
- Screenshots (required dimensions) (PNG − we can convert to WebP automatically)
- Short description (text only)
- Long description (Markdown?)

**Comment by jounih** [comment]
Cool, will take this on Monday

**Comment by jounih** [comment]
Here's a 1st draft, I'll ask people to comment so we can wrap it up and get it built

**App Center asset guidelines** 

https://www.figma.com/file/XOINhAadQHKCYghNlistQZGc/App-store-asset-guidelines?node-id=0%3A1

**Comment by luisivan** [comment]
This is perfect and ready to go to implementation phase @jounih

**Comment by luisivan** [comment]
Closing this in favor of https://github.com/aragon/hack/issues/100
