### ISSUE TITLE
Aragon DAO switcher

### ISSUE THREAD

**Issue by jounih** [aragon/design#9]
Edit: Added DAO info and blockies.

The proposal is to replace the Aragon logo on the top left with the currently viewed DAO name, as well as a dropdown accessing info/settings for currently selected DAO, list of DAOs associated to your connected provider address, and a link to manage that list.

This helps users understand which DAO they are currently viewing, and helps them to be able to easily switch between DAOs they participate in.

For the DAO icon we can use a blocky.

Prototype:

[https://invis.io/DHOFEVANYKT](https://invis.io/DHOFEVANYKT)

Design:

![webapp-1366px - dao switcher 2x](https://user-images.githubusercontent.com/10109867/46538316-fcc0e000-c8b3-11e8-8ff6-d994b951836f.jpg)
![webapp-1366px - dao switcher dropdown 2x](https://user-images.githubusercontent.com/10109867/46538327-05191b00-c8b4-11e8-89bb-572205f8f60c.jpg)

@sohkai can you help me create a bounty for implementing this?

**Comment by sohkai** [comment]
Looping in @Quazia for making bounties as well.

**Comment by osarrouy** [comment]
Hi guys,

I was also thinking about the ability to introduce hierarchy in the DAO picker. Maybe is this too much pando centric but I think it would be cool, for instance, to be able to identify / browse trough a root repo DAO and then its forks and so on. If one work on multiple 'branches' on the same repo - which acts as differents DAO - that could be pretty useful to keeps things clear and kind of visually organized.

Just an idea - maybe a stupid one - but wanted to share it with you if you guys have feedback / opinion on this :)

**Comment by jounih** [comment]
@osarrouy could be nice!

We have been also discussing nested DAOs - and getting rid of the term DAO altogether in favour of "Org" which is probably more understandable for normal people.

Will think about the branching and update the designs once we have something concrete.

**Comment by sohkai** [comment]
@osarrouy I've made https://github.com/aragon/design/issues/15 for this, to add this functionality as a later design iteration.

**Comment by osarrouy** [comment]
@jounih @sohkai Super cool. I guess that's not the more urging feature but that would definitely help at some point :)
